export const ROUTES = {
  PUBLIC: {
    LANDING: '/',
    LOGIN: '/login',
    REGISTER: '/register',
    FORGOT_PASSWORD: '/forgot-password',
    UNAUTHORIZED: '/unauthorized',
    NOT_FOUND: '/404',
  },
  ADMIN: {
    DASHBOARD: '/admin/live-tracking',
    LIVE_TRACKING: '/admin/live-tracking',
    APPROVALS: '/admin/approvals',
    ROUTES: '/admin/routes',
    SHUTTLES: '/admin/shuttles',
    DRIVERS: '/admin/drivers',
    SCHEDULES: '/admin/schedules',
    USERS: '/admin/users',
    EXPENSES: '/admin/expenses',
    COMPLAINTS: '/admin/complaints',
    REPORTS: '/admin/reports',
    ANALYTICS: '/admin/analytics',
    SETTINGS: '/admin/settings',
  },
  EMPLOYEE: {
    DASHBOARD: '/employee/dashboard',
    BOOKING: '/employee/booking',
    PASS: '/employee/pass',
    EXPENSES: '/employee/expenses',
    COMPLAINTS: '/employee/complaints',
    TRACK: '/employee/track',
  },
  DRIVER: {
    DASHBOARD: '/driver/dashboard',
    NAVIGATION: '/driver/navigation',
    CHECKIN: '/driver/checkin',
    COMPLAINTS: '/driver/complaints',
  },
} as const;
